# Generated by Django 4.0.3 on 2022-04-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bancos',
            fields=[
                ('codigo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_inst', models.CharField(max_length=500)),
            ],
        ),
    ]
